name: Deploy to Yandex Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Деплой функции с помощью yc-actions/yc-sls-functo
      - name: Deploy Function
        uses: yc-actions/yc-sls-function@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_FUNCTIONS_JSON_CRED }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: ${{ secrets.FUNCTION_NAME }}
          runtime: 'python311'
          memory: '256Mb'
          entrypoint: 'main.handler'
          environment: >-
            TELEGRAM_TOKEN=${{secrets.INFO_GASOILCENTER_BOT_TOKEN}},DRILLING_SHEET_ID=${{secrets.DRILLING_SHEET_ID }},COMPLETION_SHEET_ID=${{secrets.COMPLETION_SHEET_ID}},CREDS_URL=${{secrets.GOOGLE_CLOUD_REGIONAL_JSON }},YDB_KEY_URL=${{secrets.KEY_JSON }},YDB_ENDPOINT=${{secrets.YDB_ENDPOINT }},YDB_DATABASE=${{secrets.YDB_DATABASE }}
          include: |
            main.py
            bot.py
            services.py
            utils.py
            requirements.txt
